server:
  port: 8099

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    routes:
      - id: order-service
        uri: lb://orderservice
        predicates:
          - Path=/order/**
      - id: user-service
        uri: lb://userservice
        predicates:
          - Path=/user/**
  application:
    name: gateway
